### ISSUE TITLE
Not using BN?

### ISSUE THREAD

**Issue by mzy97** [sshan-zhao/ACMNet#1]
Thank you for sharing your work.

In your model, conv + Relu formulate a conv block, but in common practice, it is conv + BN + Relu, why you not using BN in the whole network?

**Comment by sshan-zhao** [comment]
> Thank you for sharing your work.

Hi,
Actually, I tried to use the BatchNorm, but I got worse results. BTW, some works also do not use the operation.

**Comment by mzy97** [comment]
another question: in your code here
![image](https://user-images.githubusercontent.com/31816690/93288377-4dfedb80-f80e-11ea-9c1a-f7a258254da5.png)
if downsample set True, it will get 4x smaller spatial size than the input. But in the graph attention part, 1/2 size feature maps are enhanced. and in the end, 1/2 and 1/4 spatial size feature maps are added. Am I missing some key operation?

Plus, how to decide the number of samples used by knn graph attention operation? And samples and knn points are all observed points (valid points in input)?

**Comment by sshan-zhao** [comment]
> another question: in your code here
> ![image](https://user-images.githubusercontent.com/31816690/93288377-4dfedb80-f80e-11ea-9c1a-f7a258254da5.png)
> if downsample set True, it will get 4x smaller spatial size than the input. But in the graph attention part, 1/2 size feature maps are enhanced. and in the end, 1/2 and 1/4 spatial size feature maps are added. Am I missing some key operation?
> 
> Plus, how to decide the number of samples used by knn graph attention operation? And samples and knn points are all observed points (valid points in input)?
"it will get 4x smaller spatial size than the input." => how?
"how to decide the number of samples used by knn graph attention operation" => pls refer to the ablation study

**Comment by sshan-zhao** [comment]
> another question: in your code here
> ![image](https://user-images.githubusercontent.com/31816690/93288377-4dfedb80-f80e-11ea-9c1a-f7a258254da5.png)
> if downsample set True, it will get 4x smaller spatial size than the input. But in the graph attention part, 1/2 size feature maps are enhanced. and in the end, 1/2 and 1/4 spatial size feature maps are added. Am I missing some key operation?
> 
> Plus, how to decide the number of samples used by knn graph attention operation? And samples and knn points are all observed points (valid points in input)?

"it will get 4x smaller spatial size than the input." => how?
"how to decide the number of samples used by knn graph attention operation" => pls refer to the ablation study

**Comment by mzy97** [comment]
> > another question: in your code here
> > ![image](https://user-images.githubusercontent.com/31816690/93288377-4dfedb80-f80e-11ea-9c1a-f7a258254da5.png)
> > if downsample set True, it will get 4x smaller spatial size than the input. But in the graph attention part, 1/2 size feature maps are enhanced. and in the end, 1/2 and 1/4 spatial size feature maps are added. Am I missing some key operation?
> > Plus, how to decide the number of samples used by knn graph attention operation? And samples and knn points are all observed points (valid points in input)?
> 
> "it will get 4x smaller spatial size than the input." => how?
> "how to decide the number of samples used by knn graph attention operation" => pls refer to the ablation study

if downsample set true, stride variable will be 2, in each modality branch, 2 stride conv layer applied to it. (eg. d_conv0 and d_conv1) so 1/4 size output will get.But graph operation operate in 1/2 spatial size scale

**Comment by sshan-zhao** [comment]
The two operations are applied into the input respectively
2020年9月16日 +1000 PM11:40 mzy97 <notifications@github.com>，写道：
