### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by cnexah** [sshan-zhao/ACMNet#6]
Thank you for sharing the code! Excellent work!
Would it be possible to provide the pre-trained models?

**Comment by sshan-zhao** [comment]
> Thank you for sharing the code! Excellent work!
> Would it be possible to provide the pre-trained models?

Hi,
I have provide the pertained models in the project: model.pth and model_64.pth

**Comment by cnexah** [comment]
Thank you very much!
